version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: mariadb
    restart: always
    volumes:
      - ./hackfromgarage2.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: toor
      MYSQL_DATABASE: garage
    ports:
      - "8888:3306"  